package com.demo.common.model;

import com.demo.common.model.base.BaseBlogaaa;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blogaaa extends BaseBlogaaa<Blogaaa> {
	public static final Blogaaa dao = new Blogaaa();
}
